local/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () { return redirect('/dashboard');});

Route::auth();

Route::group(['prefix' => 'dashboard', 'as' => 'home.', 'middleware' => 'dashboard'], function() {   
	Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);     
});
/* Admin */
Route::group(['prefix' => 'dashboard/admin', 'as' => 'admin.', 'middleware' => 'dashboard'], function() {
	// Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);
	Route::get('/config', ['as' => 'config', 'uses' => 'UserController@config']);
	Route::post('/update', ['as' => 'update-config', 'uses' => 'UserController@updateConfig']);
});

//Usuario
Route::group(['prefix' => 'dashboard/usuario', 'as' => 'user.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'UserController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'UserController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'UserController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'UserController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'UserController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'UserController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'UserController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'UserController@destroy']); 	  
});

//Add
Route::group(['prefix' => 'dashboard/adicionar', 'as' => 'add.', 'middleware' => 'dashboard'], function() {
	Route::get('/novo-email', ['as' => 'add-email', 'uses' => 'AddController@addEmail']);
	Route::get('/novo-telefone', ['as' => 'add-phone', 'uses' => 'AddController@addPhone']); 
	Route::get('/novo-arquivo', ['as' => 'add-file', 'uses' => 'AddController@addFile']);	
	Route::get('/nova-conta', ['as' => 'add-account', 'uses' => 'AddController@addAccount']);
	Route::get('/novo-contato', ['as' => 'add-contact', 'uses' => 'AddController@addContact']);
	Route::get('/novo-telefone-contato', ['as' => 'add-contact-phone', 'uses' => 'AddController@addContactPhone']);
	Route::get('/novo-email-contato', ['as' => 'add-contact-email', 'uses' => 'AddController@addContactEmail']);
	
});

//Empresa
Route::group(['prefix' => 'dashboard/empresa', 'as' => 'company.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'CompanyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'CompanyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'CompanyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'CompanyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'CompanyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'CompanyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'CompanyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'CompanyController@destroy']); 	
	Route::get('{id}/selecao', ['as' => 'selection', 'uses' => 'CompanyController@selection']);   
});

//Location
Route::group(['prefix' => 'dashboard/locatizacao', 'as' => 'location.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'LocationController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'LocationController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'LocationController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'LocationController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'LocationController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'LocationController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'LocationController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'LocationController@destroy']); 	
});

//Fornecedor
Route::group(['prefix' => 'dashboard/fornecedor', 'as' => 'provider.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'ProviderController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'ProviderController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'ProviderController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'ProviderController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'ProviderController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'ProviderController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'ProviderController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'ProviderController@destroy']); 	
});

//Family
Route::group(['prefix' => 'dashboard/familia', 'as' => 'family.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'FamilyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'FamilyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'FamilyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'FamilyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'FamilyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'FamilyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'FamilyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'FamilyController@destroy']); 	
});

//Fabricante
Route::group(['prefix' => 'dashboard/fabricante', 'as' => 'fabricator.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'FabricatorController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'FabricatorController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'FabricatorController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'FabricatorController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'FabricatorController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'FabricatorController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'FabricatorController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'FabricatorController@destroy']); 	
});

//Equipamentos 
Route::group(['prefix' => 'dashboard/bens', 'as' => 'property.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'PropertyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'PropertyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'PropertyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'PropertyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'PropertyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'PropertyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'PropertyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'PropertyController@destroy']); 	
});

//Tipo de Os 
Route::group(['prefix' => 'dashboard/tipo-os', 'as' => 'type-os.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'TypeOsController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'TypeOsController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'TypeOsController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'TypeOsController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'TypeOsController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'TypeOsController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'TypeOsController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'TypeOsController@destroy']); 	
});

//Ordem de Serviço 
Route::group(['prefix' => 'dashboard/ordem-servico', 'as' => 'order.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'OrderController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'OrderController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'OrderController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'OrderController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'OrderController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'OrderController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'OrderController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'OrderController@destroy']); 	
	Route::get('{id}/cancelar', ['as' => 'confirm-cancel', 'uses' => 'OrderController@confirmCancel']);
	Route::post('{id}/cancelar', ['as' => 'cancel', 'uses' => 'OrderController@cancel']); 	
	Route::get('{id}/encerrar', ['as' => 'confirm-done', 'uses' => 'OrderController@confirmDone']);
	Route::post('{id}/encerrar', ['as' => 'done', 'uses' => 'OrderController@done']); 	
	Route::get('/imprimir', ['as' => 'impress', 'uses' => 'OrderController@impress']);
});

Route::group(['prefix' => 'dashboard/agenda', 'as' => 'schedule.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'ScheduleController@index']);
	Route::get('/por-data', ['as' => 'get-by-day', 'uses' => 'ScheduleController@getByDay']);
});

//City
Route::group(['prefix' => 'dashboard/cidade', 'as' => 'city.', 'middleware' => 'dashboard'], function() {

local/app/Models/Order.php
<?php

namespace App\Models;


use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
Use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model {
    
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'orders';
    protected $fillable = ['activity', 'observation', 'date_open', 'date_start_order', 'date_close', 'urgent', 'status', 'commentary', 'type_os_id', 'property_id', 'provider_id', 'company_id', 'user_id'];

    // Relationships
    public function typeOs() {
        return $this->hasOne('App\Models\TypeOs', 'id', 'type_os_id');
    }

    public function property() {
        return $this->hasOne('App\Models\Property', 'id', 'property_id');
    }    

    public function provider() {
        return $this->hasOne('App\Models\Provider', 'id', 'provider_id');
    }     

    public function user() {
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }     

    //Mutators
    public function getFormattedDateOpenAttribute() {
        if(!empty($this->attributes['date_open'])) {
            return date('d/m/Y', strtotime($this->attributes['date_open']) );
        }
        return "";
    }

    public function getFormattedDateStartOrderAttribute() {
        if(!empty($this->attributes['date_start_order'])) {
            return date('d/m/Y', strtotime($this->attributes['date_start_order']) );
        }
        return "";
    }

    public function getFormattedDateCloseAttribute() {
        if(!empty($this->attributes['date_close'])) {
            return date('d/m/Y h:i', strtotime($this->attributes['date_close']) );
        }
        return "";
    }

    public function getFormattedStatusAttribute() {
        if(!empty($this->status)) {
            if($this->status== 'pending')   { return 'Pendente'; }
            if($this->status== 'execution') { return 'Execução'; }
            if($this->status== 'done')      { return 'Encerrada'; }
            if($this->status== 'canceled')  { return 'Canceleda'; }
        }
        return "";
    }

	public function getFormattedUrgentAttribute() {
		return ($this['urgent'] == 1 ? 'Sim' : 'Não') ;
	}


    //Mutators
    public function setDateOpenAttribute($value) {
        $this->attributes['date_open'] = !empty($value) ? Carbon::createFromFormat('d/m/Y', $value) : null; 
    }  

    public function setDateStartOrderAttribute($value) {
        $this->attributes['date_start_order'] = !empty($value) ? Carbon::createFromFormat('d/m/Y', $value) : null; 
    }   

    public function setTotalAttribute($value) {
        $this->attributes['total'] = !empty($value) ? str_replace(",",".", str_replace(".","", $value)) : null;
    }
}

local/resources/views/dashboard/order/impress.blade.php
<style type="text/css">
h4, h5, td {
	padding-left: 5px;
	padding-top: 5px;
	font-family: Verdana;
}

.label-title {
	font-weight: bold;
}

/*Utilizado para retirar o header e o footer que são gerados na pagina de impressao*/
@page 
{
  size: auto;   /* auto is the initial value */
  margin: 0mm;  /* this affects the margin in the printer settings */
}
</style>

<div id="div-impress" style="margin: 15px 20px 15px 20px;">
	
	<h4>Ordem de Serviço</h4>
	<table  cellspacing="0" cellpadding="0" border="0">
		<tr>
			<td class="label-title"> Numero</td>
			<td> {{$order->id}}</td>
		</tr>				
		<tr>
			<td class="label-title"> Tipo da OS  </td>
			<td> {{$order->typeOs->name}}</td>
		</tr>				
		<tr>
			<td class="label-title">Data de Abertura</td>
			<td> {{ $order->formatted_date_open }} </td>
		</tr>
		<tr>
			<td class="label-title"> Data de Inicio da OS </td>
			<td> {{ $order->formatted_date_start_order }} </td>
		</tr>

		<tr>
			<td class="label-title">Data de Entrega</td>
			<td>{{ $order->formatted_date_close }}</td>
		</tr>

		<tr>
			<td class="label-title">Equipamento</td>
			<td>{{ $order->property->getNameSelect() }}</td>
		</tr>

		<tr>
			<td class="label-title">Atividade</td>
			<td>{{ $order->activity }}</td>
		</tr>

		<tr>
			<td class="label-title">Urgente</td>
			<td>{{ $order->formatted_urgent }}</td>
		</tr>

		<tr>
			<td class="label-title">Status</td>
			<td>{{ $order->formatted_status }}</td>
		</tr>

		@if(Auth::user()->administrator == 1)
			<tr>
				<td class="label-title">Usuário</td>
				<td>{{ $order->user->getFormattedName() }}</td>
			</tr>
		@endif
    </table>
	
    <br>
    <br>
    <table  cellspacing="0" cellpadding="0" border="0">
        <tr>
			<td class="label-title">Observação</td>
		</tr>
		<tr>
			<td>{{ $order->observation }}</td>
		</tr>
    </table>
    
    <br>
    <br>
    <table  cellspacing="0" cellpadding="0" border="0">
		<tr>
			<td class="label-title">Comentario</td>
		</tr>
		<tr>
			<td>{{ $order->commentary }}</td>
		</tr>
    </table>
</div>

local/resources/views/dashboard/order/index.blade.php
@extends('dashboard.layout.admin_template')
@section('header-extras')
<!-- date-picker -->
<link href="{{ asset ("/css/datepicker/bootstrap-datepicker3.standalone.css") }}" rel="stylesheet" type="text/css" />

<style type="text/css">
/*Para o Data Table*/
.dataTables_scrollHead{ overflow: visible !important; }
/*Para mostrar o scroll horizontalmente*/
.scroll-x {  overflow-x:auto; margin-right: 10px;  }
/*Alinha todos os conteudos no meio*/
.table>tbody>tr>td, 
.table>tbody>tr>th, 
.table>tfoot>tr>td, 
.table>tfoot>tr>th, 
.table>thead>tr>td, 
.table>thead>tr>th {
	vertical-align: middle;
}
/*Para arrumar onde não houver sort na coluna da tabela*/
.sorting_disabled { padding: 0px !important; }
</style>
@endsection

@section('page_title','Ordem de Serviço')
@section('page_description','Painel de Controle')


<!-- Register Button -->
@section('top-button')
<div class="breadcrumb">
	<div class="row">
		<form method="get" action="{{ route('order.index') }}" enctype="multipart/form-data">			
			<div class="col-md-3 {{ Auth::user()->administrator == 0 ? 'col-md-offset-3' : '' }} " style="padding-bottom: 5px;">
				<input type="text" class="form-control datepicker" data-mask="00/00/0000" data-mask-selectonfocus="true" data-mask-clearifnotmatch="true" placeholder="__/__/____" value="{{$start}}"/> 
				<input id="start" type="hidden" name="start" value="{{str_replace('/', '-', $start)}}"/> 
			</div>
			<div class="col-md-3" style="padding-bottom: 5px;">
				<input type="text" class="form-control datepicker" data-mask="00/00/0000" data-mask-selectonfocus="true" data-mask-clearifnotmatch="true" placeholder="__/__/____" value="{{$end}}"/> 
				<input id="end" type="hidden" name="end" value="{{str_replace('/', '-', $end)}}" /> 
			</div>
			<div class="col-md-3" style="padding-bottom: 5px;">
				<button type="submit" class="btn btn-block btn btn-default"><i class="fa fa-search fa-fw"></i>Pesquisar</button>
			</div>
		</form>
		@if(Auth::user()->administrator == 1 )   
			<div class="col-md-3">
				<a href="{{ action('OrderController@create') }}"> <button class="btn btn-block btn-success"><i class="fa fa-plus fa-fw"></i> Cadastrar</button> </a>
			</div>
		@endif
	</div>
</div>
@endsection


<!-- Content -->
@section('content')

@include('dashboard.layout.success')
@include('dashboard.layout.warning')

<div id="div-main" class='row'> 
	<div class="col-xs-12">
		<div class="box">
			<div id="div-scroll-x" class="box-body">
				<table id="tbAll" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th class="text-center">Código</th>
							<th>Tipo de OS</th>
							<th>Equipamento</th>
							<th>Data de Abertura</th>            
							<th>Data de Entrega</th>            
							<th>Status</th> 
							@if(Auth::user()->administrator == 1 )       
								<th>Usuário</th>        
							@endif
							<th class="text-center">Ação</th>            
						</tr>
					</thead>
					<tbody>
					@if(count($orders) >0)
						@foreach($orders as $order)
							<tr @if($order->urgent == 1) class="warning" @endif >
								<input type="hidden" class="id" value="{{$order->id}}">
								<td class="text-center">{{ $order->id }}</td>
								<td>{{ $order->typeOs->name }}</td> 
								<td>{{ $order->property->getNameSelect() }}</td> 
								<td data-order="{{$order->date_open}}">{{ $order->formatted_date_open }}</td> 
								<td data-order="{{$order->date_close}}21">{{ $order->formatted_date_close }}</td> 
								<td>{{ $order->formatted_status }}</td> 
								@if(Auth::user()->administrator == 1 )
									<td>{{ $order->user->getFormattedName() }}</td> 
								@endif
								<td class="action-group-button text-center" style="width: 10% !important">          
									<div class="btn-group">
										<button type="button" class="btn btn-default">Ação</button>
										<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
											<span class="caret"></span>
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<ul class="dropdown-menu dropdown-menu-right" style="min-width: 100%!important">
											<li class="dropdown-primary"><a href="{{ route('order.show', ['id' => $order->id]) }}">Ver</a></li>
											<li class="dropdown-info"><a class="btn-impress" href="javascript:void(0);">Imprimir</a></li>
											@if($order->status == 'pending' || $order->status == 'execution')
												@if(Auth::user()->administrator == 1 ) 
													<li class="dropdown-warning"><a href="{{ route('order.edit', ['id' => $order->id]) }}">Editar</a></li>
												@endif
												<li  class="dropdown-success"><a href="{{ route('order.confirm-done', ['id' => $order->id]) }}">Encerrar</a></li>
												<li  class="dropdown-warning"><a href="{{ route('order.confirm-cancel', ['id' => $order->id]) }}">Cancelar</a></li>
												<li class="divider"></li>
												@if(Auth::user()->administrator == 1 ) 
													<li class="dropdown-danger"><a href="{{ route('order.delete', ['id' => $order->id]) }}">Excluir</a></li>
												@endif
											@endif
										</ul>
									</div>
								</td>
							</tr>
						@endforeach
					@endif
					</tbody>
					<tfoot>
						<tr>
							<th class="text-center">Código</th>
							<th>Tipo de OS</th>
							<th>Equipamento</th>
							<th>Data de Abertura</th>            
							<th>Data de Entrega</th>                  
							<th>Status</th>  
							@if(Auth::user()->administrator == 1 )          
								<th>Usuário</th>  
							@endif          
							<th class="text-center">Ação</th>           
						</tr>
					</tfoot>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

<!-- Footer Extra -->
@section('footer-extras')
<!-- DataTables -->
<script src="{{ asset ("/bower_components/admin-lte/plugins/datatables/jquery.dataTables.min.js") }}"></script>
<script src="{{ asset ("/bower_components/admin-lte/plugins/datatables/dataTables.bootstrap.min.js") }}"></script>
{{-- FastClick --}}
<script src="{{ asset ("/bower_components/admin-lte/plugins/fastclick/fastclick.js") }}"></script>
{{-- DatePicker --}}
<script src="{{ asset ("/js/bootstrap-datepicker.min.js") }}"></script>
<script src="{{ asset ("/js/bootstrap-datepicker.pt-BR.js") }}"></script>
<!-- Moment.js -->
<script src="{{ asset ("/bower_components/admin-lte/plugins/daterangepicker/moment.min.js") }}"></script>
<script>
	$(function () {

		var _token = '{{csrf_token()}}'; 

		@if(Auth::user()->administrator == 1 )    
			//Inicializa Data Table
			$("#tbAll").DataTable({
				"aaSorting": [],	
				"columnDefs": [
					{ "orderable": false, "targets": [7] }
				]
			});	

		@else
			//Inicializa Data Table
			$("#tbAll").DataTable({
				"aaSorting": [],	
				"columnDefs": [
					{ "orderable": false, "targets": [6] }
				]
			});	

		@endif

		//Inicializa o Datepicker
		$('.datepicker').datepicker({
			language: 'pt-BR',
			format: 'dd/mm/yyyy',
			todayHighlight: true,
			autoclose: true,
			clearBtn: true
		}).on('changeDate', function(e) {
			$(this).next().val(moment(e.date).format('DD-MM-YYYY'));
    	});		

		//Inicializa FastClick
		FastClick.attach(document.body);

		//Ajax para obter o html da Impressão do Atendimento
		function impress(evt) {
			var id = $(this).closest('tr').find(".id").val();	
			if(id) {

				var jqxhr = $.ajax({
					url: "{{ route('order.impress') }}",
					data: {'id': id},
					dataType: 'JSON',
					type: 'GET',
					beforeSend: function(request) {
						return request.setRequestHeader('X-CSRF-Token', _token);
					}
				});
				
				jqxhr.done(function(data) {
					if(data && data.success && data.html) {
						w=window.open();
						w.document.write(data.html);
						w.print();
						w.close();

					} else {

						if(data.error) { console.log(data.error); }
					}
				});
			}
		}

		//Redesenha o datatable
		function screenResize(evt) {
			evt.preventDefault();

			//Verificar tamanho da tela
			var width = $(window).width();				

			//se a tela menor que 1024 o datatable fica com scroll horizontal
			if(width < 1024){		
				$('.action-group-button').removeAttr("style").css('min-width','100px');			
				$('#div-scroll-x').addClass('scroll-x');								
				
			} else {
				$('.action-group-button').removeAttr("style").css('width','10%');
				$('#div-scroll-x').removeClass('scroll-x');								
			}
		}				

		//Eventos
		$(document).delegate('.btn-impress','click', impress);			
		$(window).resize(screenResize);
		$(window).trigger('resize');
	});

</script>

@endsection