local/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () { return redirect('/dashboard');});

Route::auth();

Route::group(['prefix' => 'dashboard', 'as' => 'home.', 'middleware' => 'dashboard'], function() {   
	Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);     
});
/* Admin */
Route::group(['prefix' => 'dashboard/admin', 'as' => 'admin.', 'middleware' => 'dashboard'], function() {
	// Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);
	Route::get('/config', ['as' => 'config', 'uses' => 'UserController@config']);
	Route::post('/update', ['as' => 'update-config', 'uses' => 'UserController@updateConfig']);
});

//Usuario
Route::group(['prefix' => 'dashboard/usuario', 'as' => 'user.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'UserController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'UserController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'UserController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'UserController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'UserController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'UserController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'UserController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'UserController@destroy']); 	  
});

//Add
Route::group(['prefix' => 'dashboard/adicionar', 'as' => 'add.', 'middleware' => 'dashboard'], function() {
	Route::get('/novo-email', ['as' => 'add-email', 'uses' => 'AddController@addEmail']);
	Route::get('/novo-telefone', ['as' => 'add-phone', 'uses' => 'AddController@addPhone']); 
	Route::get('/novo-arquivo', ['as' => 'add-file', 'uses' => 'AddController@addFile']);	
	Route::get('/nova-conta', ['as' => 'add-account', 'uses' => 'AddController@addAccount']);
	Route::get('/novo-contato', ['as' => 'add-contact', 'uses' => 'AddController@addContact']);
	Route::get('/novo-telefone-contato', ['as' => 'add-contact-phone', 'uses' => 'AddController@addContactPhone']);
	Route::get('/novo-email-contato', ['as' => 'add-contact-email', 'uses' => 'AddController@addContactEmail']);
	
});

//Empresa
Route::group(['prefix' => 'dashboard/empresa', 'as' => 'company.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'CompanyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'CompanyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'CompanyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'CompanyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'CompanyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'CompanyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'CompanyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'CompanyController@destroy']); 	
	Route::get('{id}/selecao', ['as' => 'selection', 'uses' => 'CompanyController@selection']);   
});

//Location
Route::group(['prefix' => 'dashboard/locatizacao', 'as' => 'location.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'LocationController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'LocationController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'LocationController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'LocationController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'LocationController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'LocationController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'LocationController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'LocationController@destroy']); 	
});

//Fornecedor
Route::group(['prefix' => 'dashboard/fornecedor', 'as' => 'provider.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'ProviderController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'ProviderController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'ProviderController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'ProviderController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'ProviderController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'ProviderController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'ProviderController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'ProviderController@destroy']); 	
});

//Family
Route::group(['prefix' => 'dashboard/familia', 'as' => 'family.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'FamilyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'FamilyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'FamilyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'FamilyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'FamilyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'FamilyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'FamilyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'FamilyController@destroy']); 	
});

//Fabricante
Route::group(['prefix' => 'dashboard/fabricante', 'as' => 'fabricator.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'FabricatorController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'FabricatorController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'FabricatorController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'FabricatorController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'FabricatorController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'FabricatorController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'FabricatorController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'FabricatorController@destroy']); 	
});

//Equipamentos 
Route::group(['prefix' => 'dashboard/bens', 'as' => 'property.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'PropertyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'PropertyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'PropertyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'PropertyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'PropertyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'PropertyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'PropertyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'PropertyController@destroy']); 	
});

//Tipo de Os 
Route::group(['prefix' => 'dashboard/tipo-os', 'as' => 'type-os.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'TypeOsController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'TypeOsController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'TypeOsController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'TypeOsController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'TypeOsController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'TypeOsController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'TypeOsController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'TypeOsController@destroy']); 	
});

//Ordem de Serviço 
Route::group(['prefix' => 'dashboard/ordem-servico', 'as' => 'order.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'OrderController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'OrderController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'OrderController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'OrderController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'OrderController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'OrderController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'OrderController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'OrderController@destroy']); 	
	Route::get('{id}/cancelar', ['as' => 'confirm-cancel', 'uses' => 'OrderController@confirmCancel']);
	Route::post('{id}/cancelar', ['as' => 'cancel', 'uses' => 'OrderController@cancel']); 	
	Route::get('{id}/encerrar', ['as' => 'confirm-done', 'uses' => 'OrderController@confirmDone']);
	Route::post('{id}/encerrar', ['as' => 'done', 'uses' => 'OrderController@done']); 	
	Route::get('/imprimir', ['as' => 'impress', 'uses' => 'OrderController@impress']);
});

Route::group(['prefix' => 'dashboard/agenda', 'as' => 'schedule.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'ScheduleController@index']);
	Route::get('/por-data', ['as' => 'get-by-day', 'uses' => 'ScheduleController@getByDay']);
});

//City
Route::group(['prefix' => 'dashboard/cidade', 'as' => 'city.', 'middleware' => 'dashboard'], function() {

local/app/Models/TypeOs.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TypeOs extends Model {
    
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'type_os';
    protected $fillable = ['name','active', 'company_id'];
    
    //Acessors
    public function getFormattedActiveAttribute() {
        if(isset($this->active)) {
            return $this->active == 1 ? "Sim" : "Não";
        }
        return "";
    }
}

local/app/Http/Controllers/TypeOsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\TypeOs;
use Auth;
use Gate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;

class TypeOsController extends Controller
{
	public function index() {
		try{
		
			$types = TypeOs::where('company_id', Auth::user()->company->id)->orderBy('name')->get(); 
			return view('dashboard.type_os.index')->with(['types'=> $types]);

		} catch(\Exception $e) {
			dd($e->getMessage());
			abort(500);
		}
	}

	public function create() {
		try{
		
			return view('dashboard.type_os.edit')->with([
				'page_description' 	=> 'Cadastrar',
				'route'				=> ['name' => 'type-os.store' , 'params' => [] ]
			]);

		} catch(\Exception $e) {
			abort(500);
		}
	}


	public function store(Request $request) { 
		try{
			//Validação de erros
			$errors = '';
			//verifico todos os dados de endereco
			if($request->name == ''){  $errors .= 'O campo Nome é obrigatório. <br/>';  } 

			if($errors != ''){
                \Session::flash('warning_message', $errors);
                return back();
			}   
			
			//Verifica se o Nome ja existe
			$name_count = TypeOs::where('name','=' , $request->name)
			->where('company_id', Auth::user()->company->id)
			->count(); 
			
			if($name_count > 0) { $errors .= 'O Nome já esta cadastrado. <br/>'; }

			if($errors != ''){
				\Session::flash('warning_message', $errors);
				return back();
			}   

			$type_os = TypeOs::create([
				'name' 		=> $request->name, 
				'active' 	=> $request->active,
				'company_id'=> Auth::user()->company->id
			]);
			if(isset($type_os)) {
				\Session::flash('success_message', 'Tipo de OS cadastrada com sucesso');
				return \Redirect::route('type-os.index');  
			}

		} catch(\Exception $e) {
			abort(500); 
		}
	}

	public function edit($id) {
		try {

			$type_os= TypeOs::find($id);
			if(isset($type_os)) { 
				return view('dashboard.type_os.edit')->with([
					'type' 				=> $type_os,
					'page_description' 	=> 'Editar',
					'route'				=> ['name' => 'type-os.update', 'params' => ['id' => $type_os->id]]
				]);
			}

			\Session::flash('warning_message', 'Tipo de OS não encontrada');
            return back();

		} catch(\Exception $e) {
			abort(500);
		}
	}

	public function update(Request $request, $id) {  
		try{

			$type_os = TypeOs::find($id); 
			if(isset($type_os)) {

				//Validação de erros
				$errors = '';
				//verifico todos os dados de endereco
				if($request->name == ''){  $errors .= 'O campo Nome é obrigatório. <br/>';  } 

				if($errors != ''){
					\Session::flash('warning_message', $errors);
					return back();
				} 
				
				//Verifica se o Nome ja existe
				$name_count = TypeOs::where('name','=' , $request->name)
				->where('company_id', Auth::user()->company->id)
				->where('id', '!=', $type_os->id)
				->count(); 
				
				if($name_count > 0) { $errors .= 'O Nome já esta cadastrado. <br/>'; }
				
				if($errors != ''){
					\Session::flash('warning_message', $errors);
					return back();
				} 
				
				$type_os->update([
					'name' 		=> $request->name, 
					'active' 	=> $request->active,
					'company_id'=> Auth::user()->company->id
				]);

				\Session::flash('success_message', 'Tipo de OS atualizado com sucesso');
				return back(); 
			}

			\Session::flash('warning_message', 'Tipo de OS não encontrada');
            return back();

		} catch(\Exception $e) {
			dd($e->getTrace());
            abort(500);
		}
	}

	
	public function show($id) {
		try {

			$type_os= TypeOs::find($id);
			if(isset($type_os)) { 
				return view('dashboard.type_os.edit')->with([
					'type'	 			=> $type_os,
					'page_description' 	=> 'Ver',
					'route'				=> ['name' => 'type-os.edit', 'params' => ['id' => $type_os->id]],
					'show'				=> true
				]);
			}

			\Session::flash('warning_message', 'Tipo de OS não encontrada');
            return back();

		} catch(\Exception $e) {
			abort(500);
		}
	}

	public function delete($id) {
		try {

			$type_os= TypeOs::find($id);
			if(isset($type_os)) { 
				return view('dashboard.layout.delete')->with([
					'page_title' 	=> 'Tipo de Os',
					'route'			=> ['name' => 'type-os.destroy', 'params' => ['id' => $type_os->id]],
					'fields' => [
						['col' => '6', 'title' => 'Nome', 'value' => $type_os->name]
					]
				]);
			}

			\Session::flash('warning_message', 'Tipo de OS não encontrada');
            return back();

		} catch(\Exception $e) {
			abort(500);
		}
	}	

	public function destroy(Request $request, $id) {
		try{
			$type_os= TypeOs::find($id);  
			if(isset($type_os)) {
				$type_os->delete();

				\Session::flash('success_message', 'Tipo de OS removida com sucesso');
				return \Redirect::route('type-os.index');  
			}
			
			\Session::flash('warning_message', 'Tipo de OS não encontrada');
			return \Redirect::route('type-os.index');  

		} catch (\Exception $e) {
            abort(500);			
		}
	}
}

local/resources/views/dashboard/type_os/edit.blade.php
@extends('dashboard.layout.admin_template')
@section('header-extras')
@endsection

@section('page_title','Tipo de OS')
@section('page_description', $page_description)

@section('content')

@include('dashboard.layout.success')
@include('dashboard.layout.warning')

<div id="div-main">
@if(!isset($show))
	<form method="post" action="{{ route($route['name'], $route['params']) }}" enctype="multipart/form-data"> 
		<input type="hidden" name="_token" value="{{csrf_token()}}">	
@else
	<form method="get" action="{{ route($route['name'], $route['params']) }}" enctype="multipart/form-data"> 
@endif	 
		<input type="hidden" name="_token" value="{{csrf_token()}}">		
		<div class="box box-default">
			{{-- Dados Iniciais --}}
			<div class="box-header with-border">
				<h3 class="box-title">Dados Cadastrais</h3>
				<div class="box-tools pull-right">
					<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus bt-plus"></i></button>
				</div>
			</div>

			<div class="box-body">
				<div class="row">
					{{-- Nome --}}	
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">Nome @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif  </label>
							<input type="text" class="form-control" @if(!isset($show)) name="name" @endif @if(isset($type)) value="{{ $type->name }}" @endif @if(isset($show)) readonly @else required @endif/>
						</div>  
					</div>
					{{--  Active  --}}
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">Ativo  @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif  </label>
							@if(isset($show))
								<input type="text" class="form-control" value="{{ $type->formatted_active }}" readonly />
							@else
								<select @if(!isset($show)) name="active" @endif class="form-control" style="width: 100%"  @if(isset($show)) readonly @else required @endif>
									<option value="">Selecione</option>
									<option value="0" @if(isset($type) && $type->active == '0') selected @endif>Não</option>
									<option value="1" @if((isset($type) && $type->active == '1')  || !isset($type)) selected @endif>Sim</option>		
								</select>
							@endif
						</div> 
					</div>	
				</div>	
			</div>	
		</div>			

@if(!isset($show))
		{{-- Botão --}}
		<div class="box box-default">
			<div class="box-footer">      
				<button type="submit" onclick="abrir()" class="btn btn-sm btn-success"><i class="fa fa-save fa-fw"></i> Salvar</button>
			</div>
		</div>
	</form>
@else
		{{-- Botão --}}
		<div class="box box-default">
			<div class="box-footer">		
			<button type="submit" onclick="abrir()" class="btn btn-sm btn-primary"><i class="fa fa-edit fa-fw"></i> Editar</button>
			</div>
		</div>
	</form>
@endif
</div>

@endsection

@section('footer-extras')

<!-- FastClick -->
<script src="{{ asset ("/bower_components/admin-lte/plugins/fastclick/fastclick.js") }}"></script>

<script>
	$(document).ready(function() {
		//Inicializa FastClick
		FastClick.attach(document.body);	
	}); 
</script>

@endsection

local/resources/views/dashboard/type_os/index.blade.php
@extends('dashboard.layout.admin_template')
@section('header-extras')
<style type="text/css">
/*Para o Data Table*/
.dataTables_scrollHead{ overflow: visible !important; }
/*Para mostrar o scroll horizontalmente*/
.scroll-x {  overflow-x:auto; margin-right: 10px;  }
/*Alinha todos os conteudos no meio*/
.table>tbody>tr>td, 
.table>tbody>tr>th, 
.table>tfoot>tr>td, 
.table>tfoot>tr>th, 
.table>thead>tr>td, 
.table>thead>tr>th {
	vertical-align: middle;
}
/*Para arrumar onde não houver sort na coluna da tabela*/
.sorting_disabled { padding: 0px !important; }
</style>
@endsection

@section('page_title','Tipo de OS')
@section('page_description','Painel de Controle')


<!-- Register Button -->
@section('top-button')

<div class="breadcrumb">
	<div class="row">
		<div class="col-md-6" style="margin-bottom: 5px;">
			<a href="{{ action('TypeOsController@index') }}" > <button class="btn btn-block btn btn-default"><i class="fa fa-repeat fa-fw"></i> Atualizar</button> </a>
		</div>
		<div class="col-md-6">
			<a href="{{ action('TypeOsController@create') }}"> <button class="btn btn-block btn-success"><i class="fa fa-plus fa-fw"></i> Cadastrar</button> </a>
		</div>
	</div>
</div>
@endsection


<!-- Content -->
@section('content')

@include('dashboard.layout.success')
@include('dashboard.layout.warning')

<div id="div-main" class='row'> 
	<div class="col-xs-12">
		<div class="box">
			<div id="div-scroll-x" class="box-body">
				<table id="tbAll" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Nome</th>
							<th class="text-center">Ação</th>            
						</tr>
					</thead>
					<tbody>
					@if(count($types) >0)
						@foreach($types as $type)
							<tr @if($type->active == 0) class="warning" @endif >
								<td>{{ $type->name }}</td>
								<td class="action-group-button text-center" style="width: 10% !important">          
									<div class="btn-group">
										<button type="button" class="btn btn-default">Ação</button>
										<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
											<span class="caret"></span>
											<span class="sr-only">Toggle Dropdown</span>
										</button>
										<ul class="dropdown-menu dropdown-menu-right" style="min-width: 100%!important">
											<li class="dropdown-primary"><a href="{{ route('type-os.show', ['id' => $type->id]) }}">Ver</a></li>
											<li class="dropdown-warning"><a href="{{ route('type-os.edit', ['id' => $type->id]) }}">Editar</a></li>
											<li class="divider"></li>
											<li class="dropdown-danger"><a href="{{ route('type-os.delete', ['id' => $type->id]) }}">Excluir</a></li>
										</ul>
									</div>
								</td>
							</tr>
						@endforeach
					@endif
					</tbody>
					<tfoot>
						<tr>
							<th>Nome</th>
							<th class="text-center">Ação</th>           
						</tr>
					</tfoot>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
@endsection

<!-- Footer Extra -->
@section('footer-extras')
<!-- DataTables -->
<script src="{{ asset ("/bower_components/admin-lte/plugins/datatables/jquery.dataTables.min.js") }}"></script>
<script src="{{ asset ("/bower_components/admin-lte/plugins/datatables/dataTables.bootstrap.min.js") }}"></script>
{{-- FastClick --}}
<script src="{{ asset ("/bower_components/admin-lte/plugins/fastclick/fastclick.js") }}"></script>

<script>
	$(function () {

		//Inicializa Data Table
		$("#tbAll").DataTable({
			"aaSorting": [],	
			"columnDefs": [
				{ "orderable": false, "targets": [1] }
			]
		});			

		//Inicializa FastClick
		FastClick.attach(document.body);

		//Redesenha o datatable
		function screenResize(evt) {
			evt.preventDefault();

			//Verificar tamanho da tela
			var width = $(window).width();				

			//se a tela menor que 1024 o datatable fica com scroll horizontal
			if(width < 1024){		
				$('.action-group-button').removeAttr("style").css('min-width','100px');			
				$('#div-scroll-x').addClass('scroll-x');								
				
			} else {
				$('.action-group-button').removeAttr("style").css('width','10%');
				$('#div-scroll-x').removeClass('scroll-x');								
			}
		}				

		//eventos		
		$(window).resize(screenResize);
		$(window).trigger('resize');
	});

</script>

@endsection