local/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () { return redirect('/dashboard');});

Route::auth();

Route::group(['prefix' => 'dashboard', 'as' => 'home.', 'middleware' => 'dashboard'], function() {   
	Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);     
});
/* Admin */
Route::group(['prefix' => 'dashboard/admin', 'as' => 'admin.', 'middleware' => 'dashboard'], function() {
	// Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);
	Route::get('/config', ['as' => 'config', 'uses' => 'UserController@config']);
	Route::post('/update', ['as' => 'update-config', 'uses' => 'UserController@updateConfig']);
});

//Usuario
Route::group(['prefix' => 'dashboard/usuario', 'as' => 'user.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'UserController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'UserController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'UserController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'UserController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'UserController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'UserController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'UserController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'UserController@destroy']); 	  
});

//Add
Route::group(['prefix' => 'dashboard/adicionar', 'as' => 'add.', 'middleware' => 'dashboard'], function() {
	Route::get('/novo-email', ['as' => 'add-email', 'uses' => 'AddController@addEmail']);
	Route::get('/novo-telefone', ['as' => 'add-phone', 'uses' => 'AddController@addPhone']); 
	Route::get('/novo-arquivo', ['as' => 'add-file', 'uses' => 'AddController@addFile']);	
	Route::get('/nova-conta', ['as' => 'add-account', 'uses' => 'AddController@addAccount']);
	Route::get('/novo-contato', ['as' => 'add-contact', 'uses' => 'AddController@addContact']);
	Route::get('/novo-telefone-contato', ['as' => 'add-contact-phone', 'uses' => 'AddController@addContactPhone']);
	Route::get('/novo-email-contato', ['as' => 'add-contact-email', 'uses' => 'AddController@addContactEmail']);
	
});

//Empresa
Route::group(['prefix' => 'dashboard/empresa', 'as' => 'company.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'CompanyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'CompanyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'CompanyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'CompanyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'CompanyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'CompanyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'CompanyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'CompanyController@destroy']); 	
	Route::get('{id}/selecao', ['as' => 'selection', 'uses' => 'CompanyController@selection']);   
});

//Location
Route::group(['prefix' => 'dashboard/locatizacao', 'as' => 'location.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'LocationController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'LocationController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'LocationController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'LocationController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'LocationController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'LocationController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'LocationController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'LocationController@destroy']); 	
});

//Fornecedor
Route::group(['prefix' => 'dashboard/fornecedor', 'as' => 'provider.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'ProviderController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'ProviderController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'ProviderController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'ProviderController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'ProviderController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'ProviderController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'ProviderController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'ProviderController@destroy']); 	
});

//Family
Route::group(['prefix' => 'dashboard/familia', 'as' => 'family.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'FamilyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'FamilyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'FamilyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'FamilyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'FamilyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'FamilyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'FamilyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'FamilyController@destroy']); 	
});

//Fabricante
Route::group(['prefix' => 'dashboard/fabricante', 'as' => 'fabricator.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'FabricatorController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'FabricatorController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'FabricatorController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'FabricatorController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'FabricatorController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'FabricatorController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'FabricatorController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'FabricatorController@destroy']); 	
});

//Equipamentos 
Route::group(['prefix' => 'dashboard/bens', 'as' => 'property.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'PropertyController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'PropertyController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'PropertyController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'PropertyController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'PropertyController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'PropertyController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'PropertyController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'PropertyController@destroy']); 	
});

//Tipo de Os 
Route::group(['prefix' => 'dashboard/tipo-os', 'as' => 'type-os.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'TypeOsController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'TypeOsController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'TypeOsController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'TypeOsController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'TypeOsController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'TypeOsController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'TypeOsController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'TypeOsController@destroy']); 	
});

//Ordem de Serviço 
Route::group(['prefix' => 'dashboard/ordem-servico', 'as' => 'order.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'OrderController@index']);
	Route::post('/', ['as' => 'store', 'uses' => 'OrderController@store']);
	Route::get('/cadastrar', ['as' => 'create', 'uses' => 'OrderController@create']); 
	Route::get('{id}/ver', ['as' => 'show', 'uses' => 'OrderController@show']);  
	Route::get('{id}/editar', ['as' => 'edit', 'uses' => 'OrderController@edit']);
	Route::post('{id}/editar', ['as' => 'update', 'uses' => 'OrderController@update']);   
	Route::get('{id}/excluir', ['as' => 'delete', 'uses' => 'OrderController@delete']);
	Route::post('{id}/excluir', ['as' => 'destroy', 'uses' => 'OrderController@destroy']); 	
	Route::get('{id}/cancelar', ['as' => 'confirm-cancel', 'uses' => 'OrderController@confirmCancel']);
	Route::post('{id}/cancelar', ['as' => 'cancel', 'uses' => 'OrderController@cancel']); 	
	Route::get('{id}/encerrar', ['as' => 'confirm-done', 'uses' => 'OrderController@confirmDone']);
	Route::post('{id}/encerrar', ['as' => 'done', 'uses' => 'OrderController@done']); 	
	Route::get('/imprimir', ['as' => 'impress', 'uses' => 'OrderController@impress']);
});

Route::group(['prefix' => 'dashboard/agenda', 'as' => 'schedule.', 'middleware' => 'dashboard'], function() {
	Route::get('/', ['as' => 'index', 'uses' => 'ScheduleController@index']);
	Route::get('/por-data', ['as' => 'get-by-day', 'uses' => 'ScheduleController@getByDay']);
});

//City
Route::group(['prefix' => 'dashboard/cidade', 'as' => 'city.', 'middleware' => 'dashboard'], function() {

local/app/Models/Property.php
<?php

namespace App\Models;


use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
Use Illuminate\Database\Eloquent\SoftDeletes;

class Property extends Model {
    
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'property';
    protected $fillable = ['model', 'description', 'code','date_purchase', 'last_maintenance', 'nf', 'total', 'active', 'fabricator_id', 'family_id', 'provider_id', 'location_id', 'company_id'];

    // Relationships
    public function fabricator() {
        return $this->hasOne('App\Models\Fabricator', 'id', 'fabricator_id');
    }

    public function family() {
        return $this->hasOne('App\Models\Family', 'id', 'family_id');
    }     

    public function provider() {
        return $this->hasOne('App\Models\Provider', 'id', 'provider_id');
    }     

    public function location() {
        return $this->hasOne('App\Models\Location', 'id', 'location_id');
    }     

    //Mutators
    public function getFormattedTotalAttribute() {
        if($this->attributes['total'] > 0) {
           return number_format($this->attributes['total'], 2, ',', '.');
        } 
        return "0,00";
    }

    public function getFormattedDatePurchaseAttribute() {
        if(!empty($this->attributes['date_purchase'])) {
            return date('d/m/Y', strtotime($this->attributes['date_purchase']) );
        }
        return "";
    }

    public function getFormattedLastMaintenanceAttribute() {
        if(!empty($this->attributes['last_maintenance'])) {
            return date('d/m/Y', strtotime($this->attributes['last_maintenance']) );
        }
        return "";
    }
    
    public function getFormattedActiveAttribute() {
        if(isset($this->active)) {
            return $this->active == 1 ? "Sim" : "Não";
        }
        return "";
    }    

    //Mutators
    public function setDatePurchaseAttribute($value) {
        $this->attributes['date_purchase'] = !empty($value) ? Carbon::createFromFormat('d/m/Y', $value) : null; 
    }  

    public function setLastMaintenanceAttribute($value) {
        $this->attributes['last_maintenance'] = !empty($value) ? Carbon::createFromFormat('d/m/Y', $value) : null; 
    }   

    public function setTotalAttribute($value) {
        $this->attributes['total'] = !empty($value) ? str_replace(",",".", str_replace(".","", $value)) : null;
    }

    //Methods
    public function getNameSelect() {
        return $this->model. ' ('.$this->description.')';
    }
}

local/resources/views/dashboard/property/edit.blade.php
@extends('dashboard.layout.admin_template')
@section('header-extras')
<script src="{{ asset("/bower_components/admin-lte/dist/js/validadorcpf.js")}}"></script>
<script src="{{ asset("/js/validaIE.js")}}"></script>
<!-- date-picker -->
<link href="{{ asset ("/css/datepicker/bootstrap-datepicker3.standalone.css") }}" rel="stylesheet" type="text/css" />
@endsection

@section('page_title','Bens')
@section('page_description', $page_description)

@section('content')

@include('dashboard.layout.success')
@include('dashboard.layout.warning')

@if(!isset($show))
	<form method="post" action="{{ route($route['name'], $route['params']) }}" enctype="multipart/form-data"> 
		<input type="hidden" name="_token" value="{{csrf_token()}}">	
@else
	<form method="get" action="{{ route($route['name'], $route['params']) }}" enctype="multipart/form-data"> 
@endif	

	{{-- Dados da Iniciais --}}
	<div class="box box-default">
		<div class="box-header with-border">
			<h3 class="box-title">Dados Iniciais</h3>
			<div class="box-tools pull-right">
				<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus bt-plus"></i></button>
			</div>
		</div>

		<div class="box-body">
			<div class="row">
				{{--  Fabricante  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">Fabricante @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						@if(isset($show))
							<input class="form-control" value="{{ $property->fabricator->name }}" readonly/>
						@else
							<select @if(!isset($show)) name="fabricator_id" @endif class="form-control select2" tyle="width: 100%" required >
								<option value="">Selecione</option>
								@if(isset($property)) 
									<option value="{{$property->fabricator->id}}" selected>{{$property->fabricator->name}}</option>
								@endif										
								@if(count($fabricators) > 0) 
									@foreach($fabricators as $fabricator)
										<option value="{{$fabricator->id}}">{{$fabricator->name}}</option>
									@endforeach
								@endif										
							</select> 
						@endif 
					</div>   
				</div>
				{{--  Modelo  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label id="label-name" class="control-label">Modelo @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						<input type="text" @if(!isset($show)) name="model" @endif class="form-control" @if(isset($property)) value="{{ $property->model }}" @endif  @if(isset($show)) readonly @else required @endif/>
					</div>  
				</div>  
				{{--  Familia  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">Família @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						@if(isset($show))
							<input class="form-control" value="{{ $property->fabricator->name }}" readonly/>
						@else
							<select @if(!isset($show)) name="family_id" @endif class="form-control select2" tyle="width: 100%" required >
								<option value="">Selecione</option>
								@if(isset($property)) 
									<option value="{{$property->family->id}}" selected>{{$property->family->name}}</option>
								@endif										
								@if(count($families) > 0) 
									@foreach($families as $family)
										<option value="{{$family->id}}">{{$family->name}}</option>
									@endforeach
								@endif										
							</select> 
						@endif 
					</div>   
				</div>
				{{--  Descrição  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label id="label-name" class="control-label">Descrição @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						<input type="text" @if(!isset($show)) name="description" @endif class="form-control" @if(isset($property)) value="{{ $property->description }}" @endif  @if(isset($show)) readonly @else required @endif/>
					</div>  
				</div>  
				{{--  Plaqueta  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label id="label-name" class="control-label">Plaqueta @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						<input type="text" @if(!isset($show)) name="code" @endif class="form-control" @if(isset($property)) value="{{ $property->code }}" @endif  @if(isset($show)) readonly @else required @endif/>
					</div>  
				</div>  
				{{--  Fornecedor  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">Fornecedor @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						@if(isset($show))
							<input class="form-control" value="{{ $property->provider->name }}" readonly/>
						@else
							<select @if(!isset($show)) name="provider_id" @endif class="form-control select2" tyle="width: 100%" required >
								<option value="">Selecione</option>
								@if(isset($property)) 
									<option value="{{$property->provider->id}}" selected>{{$property->provider->name}}</option>
								@endif										
								@if(count($providers) > 0) 
									@foreach($providers as $provider)
										<option value="{{$provider->id}}">{{$provider->name}}</option>
									@endforeach
								@endif										
							</select> 
						@endif 
					</div>   
				</div>
				{{--  Data de Aquisição  --}}
				<div class="col-md-3">
					<div class="form-group">
						<label id="label-name" class="control-label">Data de Aquisição @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						<div class="input-group date">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" class="form-control datepicker" @if(!isset($show)) name="date_purchase" @endif data-mask="00/00/0000"  placeholder="__/__/____" data-mask-selectonfocus="true"  data-mask-clearifnotmatch="true"  @if(isset($property)) value="{{ $property->formatted_date_purchase }}" @endif  @if(isset($show)) readonly @else required @endif />
						</div>
					</div>   
				</div>
				{{--  Ultima Manutenção  --}}
				<div class="col-md-3">
					<div class="form-group">
						<label id="label-name" class="control-label">Ultima Manutenção </label>
						<div class="input-group date">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" class="form-control datepicker" @if(!isset($show)) name="last_maintenance" @endif data-mask="00/00/0000"  placeholder="__/__/____" data-mask-selectonfocus="true"  data-mask-clearifnotmatch="true"  @if(isset($property)) value="{{ $property->formatted_last_maintenance }}" @endif  @if(isset($show)) readonly @endif />
						</div>
					</div>   
				</div>
				{{--  Localização  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">Localização @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						@if(isset($show))
							<input class="form-control" value="{{ $property->location->name }}" readonly/>
						@else
							<select @if(!isset($show)) name="location_id" @endif class="form-control select2" tyle="width: 100%" required >
								<option value="">Selecione</option>
								@if(isset($property)) 
									<option value="{{$property->location->id}}" selected>{{$property->location->getFormattedName()}}</option>
								@endif										
								@if(count($locations) > 0) 
									@foreach($locations as $location)
										<option value="{{$location->id}}">{{$location->getFormattedName()}}</option>
									@endforeach
								@endif										
							</select> 
						@endif 
					</div>   
				</div>
				{{--  Nota Fiscal  --}}
				<div class="col-md-6">
					<div class="form-group">
						<label id="label-name" class="control-label">Nota Fiscal @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						<input type="text" @if(!isset($show)) name="nf" @endif class="form-control" @if(isset($property)) value="{{ $property->nf }}" @endif  @if(isset($show)) readonly @else required @endif/>
					</div>  
				</div>  
				{{--  Valor  --}}
				<div class="col-md-6"> 
					<div class="form-group">
						<label class="control-label">Valor @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup> @endif </label>
						<div class="input-group">
							<span class="input-group-addon">R$</span>
							<input type="text" @if(!isset($show)) name="total" @endif placeholder="0,00" class="form-control money" @if(isset($property)) value="{{ $property->formatted_total }}" @endif  @if(isset($show)) readonly @else required @endif/>
						</div>
					</div>
				</div>
				{{--  Ativo  --}}
				<div class="col-md-6">					
					<div class="form-group">
						<label class="control-label">Ativo @if(!isset($show)) <span style="color: red;"><sup>&bull;</sup>@endif </label>
						@if(isset($show))
							<input type="text" class="form-control" value="{{ $property->formatted_active }}" readonly />
						@else
							<select @if(!isset($show)) name="active" @endif class="form-control" style="width: 100%"  @if(isset($show)) readonly @else required @endif>
								<option value="">Selecione</option>
								<option value="0" @if(isset($property) && $property->active == '0') selected @endif>Não</option>
								<option value="1" @if((isset($property) && $property->active == '1')  || !isset($property)) selected @endif>Sim</option>		
							</select>
						@endif
					</div> 
				</div> 
			</div>
		</div>
	</div>	
@if(!isset($show))
		{{-- Botão --}}
		<div class="box box-default">
			<div class="box-footer">      
				<button type="submit" onclick="abrir()" class="btn btn-sm btn-success"><i class="fa fa-save fa-fw"></i> Salvar</button>
			</div>
		</div>
	</form>
@else
		{{-- Botão --}}
		<div class="box box-default">
			<div class="box-footer">		
			<button type="submit" onclick="abrir()" class="btn btn-sm btn-primary"><i class="fa fa-edit fa-fw"></i> Editar</button>
			</div>
		</div>
	</form>
@endif

@endsection

@section('footer-extras')
<!-- Jquery Mask -->
<script src="{{ asset ("/bower_components/jquery-mask-plugin/dist/jquery.mask.js") }}" type="text/javascript"></script>
{{-- Select2 --}}
<script src="{{ asset ("/bower_components/admin-lte/plugins/select2/select2.full.min.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/bower_components/admin-lte/plugins/select2/i18n/pt-BR.js") }}" type="text/javascript"></script>
{{-- DatePicker --}}
<script src="{{ asset ("/js/bootstrap-datepicker.min.js") }}"></script>
<script src="{{ asset ("/js/bootstrap-datepicker.pt-BR.js") }}"></script>
{{-- Mascara.js --}}
<script src="{{ asset("/bower_components/admin-lte/dist/js/mascara.js")}}"></script>
{{-- FastClick --}}
<script src="{{ asset ("/bower_components/admin-lte/plugins/fastclick/fastclick.js") }}"></script>

<script>
	$(document).ready(function() {
			//Inicializa FastClick
			FastClick.attach(document.body);
		
		@if(!isset($show))
			//Set da linguagem do select2
			$.fn.select2.defaults.set('language', 'pt-BR');

			//Inicia os plugins nos componentes
			$('.select2', '#div-main').select2();

			//Inicializa o Datepicker
			$('.datepicker').datepicker({
				language: 'pt-BR',
				format: 'dd/mm/yyyy',
				todayHighlight: true,
				autoclose: true,
				clearBtn: true
			});

			//Set da máscara do telefone
			$('.money').mask("#.##0,00", {reverse: true});
		@endif
	}); 
</script>

@endsection